[package]
name = "allsky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libasi = { version = "0.1.0", path = "./libasi" }
image = "0.24.6"