[package]
name = "libasi-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libasi_sys"
path = "lib.rs"

[dependencies]

[build-dependencies]
bindgen = "0.61.0"
